include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "lib/**/*.mocks.dart"
  errors:
    todo: info

linter:
  rules:
    prefer_single_quotes: true
    sort_pub_dependencies: false
   
