name: pin_lock

version: 0.0.1+1

description: "A full solution to local authentication: it contains authentication logic and tracks authentication-relevant data, while providing an interface for app-specific UI implementatin."

repository: https://github.com/DutchCodingCompany/pin_lock

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: 0.10.0-nullsafety.1
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  local_auth: ^1.1.1
  crypto: ^3.0.1
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  lint: ^1.5.3
  mockito: ^5.0.3
  


flutter:
  plugin:
    platforms:
      android:
        package: nl.dutchcodingcompany.pin_lock
        pluginClass: PinLockPlugin
      ios:
        pluginClass: PinLockPlugin
